on:
  push:
    branches: master

jobs:
  job1:
    uses: kasisubbarayudu/Work/.github/workflows/main.yml@master
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
        pytest -vv

