on:
  workflow_dispatch:

jobs:
  job1:
    uses: kasisubbarayudu/Work/.github/workflows/main.yml@main
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: checking out to latest repo...
      uses: actions/checkout@v3
    - name: Setting up python...
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installing dependencies...
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -vv

